apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-backup 
  namespace: etcd-backup 
  labels:
    config.example.com/name: etcd-backup
    config.example.com/component: persistantvolumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
