apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    purpose: etcd-backup
    config.example.com/name: etcd-backup
    config.example.com/component: serviceaccount 
  name: etcd-backup
  namespace: etcd-backup 
